global:
  reduction_method: SMDS
  k: 5
  repetitions: 5
  target_columns: last_prompt_token
  layers: null
  max_samples: 500

grid:
  n_components: [3]
  manifold: 
    - euclidean
    - discrete_circular
    - cluster
    - circular
    - semicircular
    - log_linear
    - log_semicircular

local:
  #### gemma-2-2b-it ####
  - path: results/gemma-2-2b-it/duration_3way.pt
    label_col: correct_duration_length

  - path: results/gemma-2-2b-it/date_3way.pt
    label_col: correct_date
    preprocess_func: datetime_to_dayofyear

  - path: results/gemma-2-2b-it/date_3way_season.pt
    label_col: correct_season_label

  - path: results/gemma-2-2b-it/date_3way_season.pt
    label_col: correct_date
    preprocess_func: datetime_to_dayofyear

  - path: results/gemma-2-2b-it/date_3way_temperature.pt
    label_col: correct_temperature_label

  - path: results/gemma-2-2b-it/date_3way_temperature.pt
    label_col: correct_date
    preprocess_func: datetime_to_dayofyear

  - path: results/gemma-2-2b-it/time_of_day_3way.pt
    label_col: correct_time
    preprocess_func: datetime_to_hour

  - path: results/gemma-2-2b-it/time_of_day_3way_phase.pt
    label_col: correct_phase_label

  - path: results/gemma-2-2b-it/periodic_3way.pt
    label_col: correct_period_length

  - path: results/gemma-2-2b-it/notable_3way.pt
    label_col: correct_date
    preprocess_func: datetime_to_year
    label_shift: -2023

  #### llama-3.2-3b-instruct ####
  - path: results/Llama-3.2-3B-Instruct/duration_3way.pt
    label_col: correct_duration_length

  - path: results/Llama-3.2-3B-Instruct/date_3way.pt
    label_col: correct_date
    preprocess_func: datetime_to_dayofyear

  - path: results/Llama-3.2-3B-Instruct/date_3way_season.pt
    label_col: correct_season_label

  - path: results/Llama-3.2-3B-Instruct/date_3way_season.pt
    label_col: correct_date
    preprocess_func: datetime_to_dayofyear

  - path: results/Llama-3.2-3B-Instruct/date_3way_temperature.pt
    label_col: correct_temperature_label

  - path: results/Llama-3.2-3B-Instruct/date_3way_temperature.pt
    label_col: correct_date
    preprocess_func: datetime_to_dayofyear

  - path: results/Llama-3.2-3B-Instruct/time_of_day_3way.pt
    label_col: correct_time
    preprocess_func: datetime_to_hour

  - path: results/Llama-3.2-3B-Instruct/time_of_day_3way_phase.pt
    label_col: correct_phase_label

  - path: results/Llama-3.2-3B-Instruct/periodic_3way.pt
    label_col: correct_period_length

  - path: results/Llama-3.2-3B-Instruct/notable_3way.pt
    label_col: correct_date
    preprocess_func: datetime_to_year
    label_shift: -2023

  #### Qwen2.5-3B-Instruct ####
  - path: results/Qwen2.5-3B-Instruct/duration_3way.pt
    label_col: correct_duration_length

  - path: results/Qwen2.5-3B-Instruct/date_3way.pt
    label_col: correct_date
    preprocess_func: datetime_to_dayofyear

  - path: results/Qwen2.5-3B-Instruct/date_3way_season.pt
    label_col: correct_season_label

  - path: results/Qwen2.5-3B-Instruct/date_3way_season.pt
    label_col: correct_date
    preprocess_func: datetime_to_dayofyear

  - path: results/Qwen2.5-3B-Instruct/date_3way_temperature.pt
    label_col: correct_temperature_label

  - path: results/Qwen2.5-3B-Instruct/date_3way_temperature.pt
    label_col: correct_date
    preprocess_func: datetime_to_dayofyear

  - path: results/Qwen2.5-3B-Instruct/time_of_day_3way.pt
    label_col: correct_time
    preprocess_func: datetime_to_hour

  - path: results/Qwen2.5-3B-Instruct/time_of_day_3way_phase.pt
    label_col: correct_phase_label

  - path: results/Qwen2.5-3B-Instruct/periodic_3way.pt
    label_col: correct_period_length

  - path: results/Qwen2.5-3B-Instruct/notable_3way.pt
    label_col: correct_date
    preprocess_func: datetime_to_year
    label_shift: -2023

  #### Llama-3.1-8B-Instruct ####
  - path: results/8B-Instruct/duration_3way
    model_name: meta-llama/Llama-3.1-8B-Instruct
    label_col: correct_duration_length

  - path: results/8B-Instruct/date_3way
    model_name: meta-llama/Llama-3.1-8B-Instruct
    label_col: correct_date
    preprocess_func: datetime_to_dayofyear

  - path: results/8B-Instruct/date_3way_season
    model_name: meta-llama/Llama-3.1-8B-Instruct
    label_col: correct_season_label

  - path: results/8B-Instruct/date_3way_temperature
    model_name: meta-llama/Llama-3.1-8B-Instruct
    label_col: correct_temperature_label

  - path: results/8B-Instruct/time_of_day_3way
    model_name: meta-llama/Llama-3.1-8B-Instruct
    label_col: correct_time
    preprocess_func: datetime_to_hour

  - path: results/8B-Instruct/time_of_day_3way_phase
    model_name: meta-llama/Llama-3.1-8B-Instruct
    label_col: correct_phase_label

  - path: results/8B-Instruct/periodic_3way
    model_name: meta-llama/Llama-3.1-8B-Instruct
    label_col: correct_period_length

  - path: results/8B-Instruct/notable_3way
    model_name: meta-llama/Llama-3.1-8B-Instruct
    label_col: correct_date
    preprocess_func: datetime_to_year
    label_shift: -2023

  #### Llama-3.1-70B-Instruct ####
  - path: results/70B-Instruct/duration_3way
    model_name: meta-llama/Llama-3.1-70B-Instruct
    label_col: correct_duration_length
    layers: [0,1,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80]
    k: 5
    repetitions: 1

  - path: results/70B-Instruct/date_3way
    model_name: meta-llama/Llama-3.1-70B-Instruct
    label_col: correct_date
    preprocess_func: datetime_to_dayofyear
    layers: [0,1,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80]
    k: 5
    repetitions: 1

  - path: results/70B-Instruct/date_3way_season
    model_name: meta-llama/Llama-3.1-70B-Instruct
    label_col: correct_season_label
    layers: [0,1,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80]
    k: 5
    repetitions: 1

  - path: results/70B-Instruct/date_3way_temperature
    model_name: meta-llama/Llama-3.1-70B-Instruct
    label_col: correct_temperature_label
    layers: [0,1,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80]
    k: 5
    repetitions: 1


  - path: results/70B-Instruct/time_of_day_3way
    model_name: meta-llama/Llama-3.1-70B-Instruct
    label_col: correct_time
    preprocess_func: datetime_to_hour
    layers: [0,1,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80]
    k: 5
    repetitions: 1

  - path: results/70B-Instruct/time_of_day_3way_phase
    model_name: meta-llama/Llama-3.1-70B-Instruct
    label_col: correct_phase_label
    layers: [0,1,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80]
    k: 5
    repetitions: 1

  - path: results/70B-Instruct/periodic_3way
    model_name: meta-llama/Llama-3.1-70B-Instruct
    label_col: correct_period_length
    layers: [0,1,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80]
    k: 5
    repetitions: 1

  - path: results/70B-Instruct/notable_3way
    model_name: meta-llama/Llama-3.1-70B-Instruct
    label_col: correct_date
    preprocess_func: datetime_to_year
    label_shift: -2023
    layers: [0,1,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80]
    k: 5
    repetitions: 1

    #### gemma-2-2b ####
  - path: results/gemma-2-2b/duration_3way.pt
    label_col: correct_duration_length

  - path: results/gemma-2-2b/date_3way.pt
    label_col: correct_date
    preprocess_func: datetime_to_dayofyear

  - path: results/gemma-2-2b/date_3way_season.pt
    label_col: correct_season_label

  - path: results/gemma-2-2b/date_3way_temperature.pt
    label_col: correct_temperature_label

  - path: results/gemma-2-2b/time_of_day_3way.pt
    label_col: correct_time
    preprocess_func: datetime_to_hour

  - path: results/gemma-2-2b/time_of_day_3way_phase.pt
    label_col: correct_phase_label

  - path: results/gemma-2-2b/periodic_3way.pt
    label_col: correct_period_length

  - path: results/gemma-2-2b/notable_3way.pt
    label_col: correct_date
    preprocess_func: datetime_to_year
    label_shift: -2023

  #### llama-3.2-3B ####
  - path: results/Llama-3.2-3B/duration_3way.pt
    label_col: correct_duration_length

  - path: results/Llama-3.2-3B/date_3way.pt
    label_col: correct_date
    preprocess_func: datetime_to_dayofyear

  - path: results/Llama-3.2-3B/date_3way_season.pt
    label_col: correct_season_label

  - path: results/Llama-3.2-3B/date_3way_temperature.pt
    label_col: correct_temperature_label

  - path: results/Llama-3.2-3B/time_of_day_3way.pt
    label_col: correct_time
    preprocess_func: datetime_to_hour

  - path: results/Llama-3.2-3B/time_of_day_3way_phase.pt
    label_col: correct_phase_label

  - path: results/Llama-3.2-3B/periodic_3way.pt
    label_col: correct_period_length

  - path: results/Llama-3.2-3B/notable_3way.pt
    label_col: correct_date
    preprocess_func: datetime_to_year
    label_shift: -2023

  #### Qwen2.5-3B ####
  - path: results/Qwen2.5-3B/duration_3way.pt
    label_col: correct_duration_length

  - path: results/Qwen2.5-3B/date_3way.pt
    label_col: correct_date
    preprocess_func: datetime_to_dayofyear

  - path: results/Qwen2.5-3B/date_3way_season.pt
    label_col: correct_season_label

  - path: results/Qwen2.5-3B/date_3way_temperature.pt
    label_col: correct_temperature_label

  - path: results/Qwen2.5-3B/time_of_day_3way.pt
    label_col: correct_time
    preprocess_func: datetime_to_hour

  - path: results/Qwen2.5-3B/time_of_day_3way_phase.pt
    label_col: correct_phase_label

  - path: results/Qwen2.5-3B/periodic_3way.pt
    label_col: correct_period_length

  - path: results/Qwen2.5-3B/notable_3way.pt
    label_col: correct_date
    preprocess_func: datetime_to_year
    label_shift: -2023